import React from "react";
import { Card, CardContent, CardFooter, CardTitle } from "@/components/ui/card";
import Image from "next/image";
import { Badge } from "@/components/ui/badge";

const popularContent = [
  {
    id: 1,
    title: "Image generated by AI",
    badge: "AI",
    image:
      "https://images.pexels.com/photos/8721198/pexels-photo-8721198.jpeg?auto=compress&cs=tinysrgb&w=600",
    count: 1100,
  },
  {
    id: 2,
    title: "Subscription for AI",
    badge: "john",
    image:
      "https://images.pexels.com/photos/5473955/pexels-photo-5473955.jpeg?auto=compress&cs=tinysrgb&w=600",
    count: 1200,
  },
];

const latestTransactions = [
  {
    id: 1,
    title: "Subscription Renewal",
    badge: "Michel Johnson",
    image:
      "https://images.pexels.com/photos/7706367/pexels-photo-7706367.jpeg?auto=compress&cs=tinysrgb&w=600",
    count: 1300,
  },
  {
    id: 2,
    title: "Payment for Services",
    badge: "Michel Johnson",
    image:
      "https://images.pexels.com/photos/4482900/pexels-photo-4482900.jpeg?auto=compress&cs=tinysrgb&w=600",
    count: 1400,
  },
  {
    id: 3,
    title: "Late fees Penalty",
    badge: "Michel",
    image:
      "https://images.pexels.com/photos/4069292/pexels-photo-4069292.jpeg?auto=compress&cs=tinysrgb&w=600",
    count: 1500,
  },
  {
    id: 4,
    title: "Funds for Child Care",
    badge: "Chashampal",
    image:
      "https://images.pexels.com/photos/933624/pexels-photo-933624.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    count: 1600,
  },
  {
    id: 5,
    title: "Expense for Utils",
    badge: "Michel Jordan",
    image:
      "https://images.pexels.com/photos/4476375/pexels-photo-4476375.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    count: 1700,
  },
];
const CardList = ({ title }: { title: string }) => {
  const list =
    title === "Popular Content" ? popularContent : latestTransactions;
  return (
    <div>
      <h1 className="text-lg font-medium mb-6">{title}</h1>
      <div className="flex flex-col gap-2">
        {list.map((item) => (
          <Card
            key={item.id}
            className="flex gap-4 items-center justify-between p-2"
          >
            <div className="w-20 h-12 rounded-sm relative overflow-hidden gap-2">
              <Image
                className="object-cover"
                src={item.image}
                alt={item.title}
                fill
              />
            </div>
            <CardContent className="flex-1 p-0">
              <CardTitle className="text-sm font-medium">
                {item.title}
              </CardTitle>
              <Badge variant={"outline"}>{item.badge}</Badge>
            </CardContent>
            <CardFooter className="p-0">{item.count / 100}k</CardFooter>
          </Card>
        ))}
      </div>
    </div>
  );
};
export default CardList;
